---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: cloudant-pvc
spec:
   capacity:
      storage: 3Gi
   accessModes:
      - ReadWriteOnce
   nfs:
      server: 192.168.20.200
      path: /media/nfs/cloudant1
---
