---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: my-release-jenkins
spec:
   capacity:
      storage: 1Gi
   accessModes:
      - ReadWriteOnce
   nfs:
      server: 192.168.20.200
      path: /nfs/jenkins
---
