---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-lxd
spec:
  ports:
  - port: 39000
---
apiVersion: v1
kind: Endpoints
metadata:
  name:  glusterfs-lxd
subsets:
  - addresses:
    - ip: xxx.xxx.xxx.xxx
    ports:
    - port: 39000
  - addresses:
    - ip: xxx.xxx.xxx.xxx
    ports:
    - port: 39000
---
