---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: jenkins-pv
   labels:
       project: devops
spec:
   capacity:
      storage: 5Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   glusterfs:
      endpoints: glusterfs-lxd     
      path: vol1 
---
