---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: my-liberty-logs-pv
spec:
   capacity:
      storage: 1Gi
   accessModes:
      - ReadWriteOnce
   nfs:
      server: 192.168.1.32
      path: /media/nfs/liberty1
---
